version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-s3: circleci/aws-s3@4.0.0
  rj-package: rhems-japan/package@0.0.81

main-filter: &main-filter
  context:
    - billsan-aws-main
  filters:
    branches:
      only: main

jobs:
  deploy-s3:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: -------------------------
      - aws-cli/setup
      - aws-s3/sync:
          arguments: --delete
          from: /
          to: s3://${S3_BUCKET_NAME}/
      - run:
          name: purge
          command: aws cloudfront create-invalidation --distribution-id ${CF_DISTRIBUTION_ID} --paths "/*"
      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
          steps:
            - rj-package/create-badge:
                app: billsan-aws
                color: green
                text: ${CIRCLE_BRANCH}

workflows:
  deploy-main:
    jobs:
      - deploy-s3:
          <<: *main-filter
