version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-s3: circleci/aws-s3@4.0.0
  rj-package: rhems-japan/package@0.0.81

main-filter: &main-filter
  filters:
    branches:
      only: main

jobs:
  deploy-s3:
    docker:
      - image: cimg/python:3.10.4
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: SHA256:D7K9VjstwPPb++QRHwU87Kvh76gaparnC9FGdWfnBlo
      - aws-cli/setup
      - aws-s3/sync:
          arguments:
            --delete
            --exclude ".git/*"
            --exclude ".circleci/*"
          from: .
          to: s3://${S3_BUCKET_NAME}

workflows:
  deploy-main:
    jobs:
      - deploy-s3:
          <<: *main-filter
